Adjective = input("Enter an adjective: ")
Nounperson = input("Enter a noun (person): ")
Nounplace = input("Enter a noun (place): ")
Verbpast = input("Enter a past verb: ")
Adverb = input("Enter an adverb: ")
Plural_noun = input("Enter a plural noun: ")
Verb = input("Enter a present verb: ")
Adjective2 = input("Enter another adjective: ")
Exclamation = input("Enter an exclamation word: ")
Number = input("Enter a number: ")
print(f" ")

print(f"It was a {Adjective} afternoon when {Nounperson} decided to cook dinner at the {Nounplace}.")
print(f"They {Verbpast} {Adverb} while chopping the {Plural_noun}.")
print(f"Then they tried to {Verb} the stew, but accidentally added {Number} cups of {Plural_noun} instead of salt!")
print(f"The dish turned out {Adjective2}.")
print(f"Everyone at the table yelled, {Exclamation}!")
print(f"And just like that, dinner was officially ruined.")